### ISSUE TITLE
Fix Bug: Colors on the wall are flipped (orange/yellow & pink/green)

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#128]

**Comment by SamuelBrander** [comment]
Figured out issue is in Frontend, going to pair program with @softconrob to solve it there, closing this issue since tests added in https://github.com/sopra-fs22-group-34/server/commit/c662dd050d16c9aefccd7b452e6f036dddf734d8 proved the issue is not in the backend
